plugins {
    id 'checkstyle'
    id 'application'
    id 'org.graalvm.buildtools.native'
}

apply plugin : "java"

application {
    mainClass = 'uk.co.flypig.Main'
}

checkstyle {
    getConfigDirectory().set(rootProject.file("checkstyle"))
    ignoreFailures = false
    showViolations = true
    toolVersion = checkstyleVersion
}

checkstyleTest {
    enabled = false // do not checkstyle test files
}

dependencies {
    implementation project(':timeago-parser')
    api project(':extractor')

    implementation 'com.squareup.okhttp3:okhttp:3.12.13'

    compileOnly 'org.projectlombok:lombok:1.18.36'
    annotationProcessor 'org.projectlombok:lombok:1.18.36'

    compileOnly 'com.dslplatform:dsl-json:2.0.2'
    annotationProcessor 'com.dslplatform:dsl-json:2.0.2'
    compileOnly 'javax.json.bind:javax.json.bind-api:1.0'
}

graalvmNative {
    binaries.all {
        // Avoid java.lang.ExceptionInInitializerError runtime error
        // See https://github.com/oracle/graal/issues/1294
        buildArgs.add('-H:+AddAllCharsets')
        // Enable network protocols
        buildArgs.add('--enable-url-protocols=http,https')
        //buildArgs.add('--parallelism=2')
        buildArgs.add('-H:DeadlockWatchdogInterval=0')
        buildArgs.add('-H:+UnlockExperimentalVMOptions')
    }
}

